project:
    name: smoothjs
    version: 1.0.0
workflow:
    statuses:
        - open
        - in-progress
        - review
        - done
        - closed
    default_status: open
templates:
    default: task
    available:
        - bug
        - feature
        - task
        - epic
        - improvement
labels:
    - name: bug
      color: '#d73a4a'
    - name: enhancement
      color: '#a2eeef'
    - name: documentation
      color: '#0075ca'
    - name: good first issue
      color: '#7057ff'
milestones: []
git:
    auto_link: true
    auto_close_keywords:
        - closes
        - fixes
        - resolves
    default_branch_prefix: feature
    branch_config:
        template: '{prefix}/{issue}-{title}'
        prefix_by_type:
            bug: bugfix
            epic: feature
            feature: feature
            hotfix: hotfix
            improvement: feature
            task: feature
        max_title_length: 50
        auto_switch: true
        auto_merge_targets:
            - main
            - master
            - develop
ui:
    colors: true
    interactive: true
    pager: auto
    format: table
storage:
    max_project_size: 1073741824
    max_attachment_size: 10485760
    max_total_attachments: 524288000
    max_attachment_age: 0
    enable_auto_cleanup: false
    warning_threshold: 80
    critical_threshold: 95
    enforce_quotas: false
    cleanup:
        enabled: false
        schedule: 0 2 * * *
        retention_days:
            closed_issues: 90
            closed_issue_attachments: 30
            history: 365
            time_entries: 365
            orphaned_attachments: 7
            empty_directories: true
        size_triggers:
            max_total_size: 0
            max_attachments_size: 0
            max_history_size: 0
            trigger_percentage: 90
        archive_before_delete: false
        archive_path: .issuemap_archive
        dry_run_mode: false
        minimum_keep:
            closed_issues: 10
            history_per_issue: 5
            time_entries_per_issue: 5
    compression:
        enabled: true
        level: 6
        min_file_size: 1024
        max_file_size: 52428800
        min_compression_ratio: 0.1
        compressible_extensions:
            - .txt
            - .log
            - .csv
            - .json
            - .xml
            - .yaml
            - .yml
            - .js
            - .py
            - .go
            - .java
            - .c
            - .cpp
            - .h
            - .hpp
            - .rb
            - .php
            - .pl
            - .sh
            - .sql
            - .html
            - .css
            - .md
            - .markdown
            - .rst
            - .tex
            - .ini
            - .conf
            - .config
            - .properties
        skip_extensions:
            - .jpg
            - .jpeg
            - .png
            - .gif
            - .webp
            - .bmp
            - .zip
            - .tar
            - .gz
            - .bz2
            - .xz
            - .7z
            - .rar
            - .mp4
            - .mp3
            - .avi
            - .mov
            - .mkv
            - .flv
            - .wav
            - .ogg
            - .pdf
            - .doc
            - .docx
            - .xls
            - .xlsx
            - .ppt
            - .pptx
            - .exe
            - .dll
            - .so
            - .dylib
        background_compression: true
        background_batch_size: 10
